# This is a basic workflow to help you get started with Actions

name: sync pages to server

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync_gitee:
    name: sync pages to server
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code from github
        uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: sync shell cmd
        run: |
          git fetch --unshallow
          git checkout gh-pages
          if [[ "${{ secrets.SERVERCHAIN_KEY }}x" != "x" ]]; then curl "https://sctapi.ftqq.com/${{ secrets.SERVERCHAIN_KEY }}.send?title=正在部署teedoc网站到服务器"; else echo "no server chain key"; fi
          SSHPATH="$HOME/.ssh"
          rm -rf "$SSHPATH"
          mkdir -p "$SSHPATH"
          echo "${{ secrets.GITEE_SYNC_ACCESSS_KEY_SERVER }}" > "$SSHPATH/id_rsa"
          chmod 600 "$SSHPATH/id_rsa"
          sudo sh -c "echo StrictHostKeyChecking no >>/etc/ssh/ssh_config"
          rsync -avz -c -r --exclude='.git' ./*  ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PATH }}/

